name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

defaults:
  run:
    shell: bash
    working-directory: go

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: '^1.13.1' # The Go version to download (if necessary) and use.
        - run: make isucari


